// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo3Xrkw94djzZXpt9-RE2pkHXJRtGpHTI',
    appId: '1:1090744554259:android:3833517a7deb0d9ad5c0e6',
    messagingSenderId: '1090744554259',
    projectId: 'traqa-2c398',
    storageBucket: 'traqa-2c398.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwGkEoMivEZQcJsnZD-3XCwvdhXQA0r-o',
    appId: '1:1090744554259:ios:1b3c99f5fecb4a56d5c0e6',
    messagingSenderId: '1090744554259',
    projectId: 'traqa-2c398',
    storageBucket: 'traqa-2c398.appspot.com',
    androidClientId: '1090744554259-75tkjvuqvom4ea8078peoth443ilo1sl.apps.googleusercontent.com',
    iosClientId: '1090744554259-6hnkv0lp9p8i83pqvhcbrpkvui5p8g4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.traqa',
  );

}